msgEmptyGNQL = "empty gnql";
msgSuccess = "success";
msgFormat = "wrong format";
andSeparater = "@";
orSeparater = "~";
thisSeparaterArr = "@[";
lastSeparater = "}]";
firstSeparater = "{";
fileSuffix = ".gnql"
deleted = "deleted"
code = "code"
IOError = "IOError"
nonDeleted = "nothing are deleted"
updated = "updated"
nonUpdated = "nothing are updated"
userUnExist = "haven't this user,please check you username"
userExist = "this user is exist,please check you username"
passwordError = "password error"
SignUpSuccess = "SignUpSuccess"
loginSuccess = "loginSuccess"
tokenUnExist = "tokenUnExist"
tokenExist = "tokenExist"
sessionUsername = "gnosqlUsername"
needToken = "need more parameters"
loginPlease = "loginPlease"
none = type(None)
path = "./"
noneArr = []
noSeparater = ","
gnosqlId = "gnosqlId"
appName = "appName"
token = "token"
rows = "rows"
where = "where"
update="update"
appIp = "appIp"
appName = "appName"
msg = "msg"
user = "user"
gnosql = "gnosql"
gnosqlIp = "gnosqlIp"
gnosqlExist = "gnosqlExist"
checkYourParameters="please check Your Parameters"
